### ISSUE TITLE
KeyError when trying to use wordpress_json

### ISSUE THREAD

**Issue by minorsecond** [stylight/python-wordpress-json#2]
Using:
* Python 3.5
* Wordpress 4.6
* wordpress_json 0.2.2
* Json Basic Authentication 0.1
* WP REST API 2.0-beta13.1
* WP REST API - Meta Endpoints 0.1.0

I tried a simple example similar to what is provided in the README:
```
url = 'http://minilogbook.com/wp-json'
user = 'minorsecond'
password = '*********'

wp = WordpressJsonWrapper(url, user, password)

posts = wp.get_posts()
```

and I get:

```
Traceback (most recent call last):
  File "/Users/rwardrup/DEV/miniLogbook/bin/slm.py", line 20, in <module>
    posts = wp.get_posts()
  File "/Users/rwardrup/miniconda3/envs/miniLogbook/lib/python3.4/site-packages/wordpress_json/__init__.py", line 69, in api_method
    return self._request(method_name, **kw)
  File "/Users/rwardrup/miniconda3/envs/miniLogbook/lib/python3.4/site-packages/wordpress_json/__init__.py", line 267, in _request
    '[%s] %s' % (http_response.json()[0].get('code'),
KeyError: 0
```

**Comment by deusprogrammer** [comment]
I am having the same error.  Any idea when this started happening so I might kick it back a commit or too?

**Comment by minorsecond** [comment]
I'm not sure. I only began experimenting with it yesterday. Let me know how I can help though.

**Comment by droustchev** [comment]
The traceback you get is a legitimate bug in the code that handles HTTP errors. I have a pull-request(https://github.com/stylight/python-wordpress-json/pull/3) up to fix that.

The error thrown is most likely a 
```shell
404 Not Found :  [rest_no_route] No route was found matching the URL and request method
```
This is because wordpress apparently changed the API endpoints for v2. Try the following instead and it should work, even with the current bug.
```python
url = 'http://minilogbook.com/wp-json/wp/v2'
``` 
I've also created a PR to fix the README(https://github.com/stylight/python-wordpress-json/pull/4).

**Comment by minorsecond** [comment]
Thanks, @droustchev 

There seems to be another issue, though I'm not sure if it's on my end: 400 bad request. I peered into the code and, if I put a print statement in line 262, it seems I am getting a response. If someone else can replicate this, I'll create another issue. 

```
http_response = requests.request(
            method,
            self.site + endpoint,
            auth=self.auth,
            params=params,
            json=data,
            headers=headers
        )

        print(http_response.content)

Traceback (most recent call last):
  File "/Users/rwardrup/DEV/miniLogbook/bin/slm.py", line 17, in <module>
    posts = wp.get_posts()
  File "/Users/rwardrup/miniconda3/envs/miniLogbook/lib/python3.4/site-packages/wordpress_json/__init__.py", line 69, in api_method
    return self._request(method_name, **kw)
  File "/Users/rwardrup/miniconda3/envs/miniLogbook/lib/python3.4/site-packages/wordpress_json/__init__.py", line 270, in _request
    http_response.json()[0].get('message'))
wordpress_json.WordpressError: 400 Bad Request :  [None] None

b'[{"id":1,"date":"2016-08-14T21:28:27","date_gmt":"2016-08-14T21:28:27","guid":{"rendered":"http:\\/\\/minilogbook.com\\/?p=1"},"modified":"2016-08-14T21:28:27","modified_gmt":"2016-08-14T21:28:27","slug":"hello-world","type":"post","link":"http:\\/\\/minilogbook.com\\/hello-world\\/","title":{"rendered":"Hello world!"},"content":{"rendered":"<p>Welcome to WordPress. This is your first post. Edit or delete it, then start writing!<\\/p>\\n"},"excerpt":{"rendered":"<p>Welcome to WordPress. This is your first post. Edit or delete it, then start writing!<\\/p>\\n"},"author":1,"featured_media":0,"comment_status":"open","ping_status":"open","sticky":false,"format":"standard","categories":[1],"tags":[],"_links":{"self":[{"href":"http:\\/\\/minilogbook.com\\/wp-json\\/wp\\/v2\\/posts\\/1"}],"collection":[{"href":"http:\\/\\/minilogbook.com\\/wp-json\\/wp\\/v2\\/posts"}],"about":[{"href":"http:\\/\\/minilogbook.com\\/wp-json\\/wp\\/v2\\/types\\/post"}],"author":[{"embeddable":true,"href":"http:\\/\\/minilogbook.com\\/wp-json\\/wp\\/v2\\/users\\/1"}],"replies":[{"embeddable":true,"href":"http:\\/\\/minilogbook.com\\/wp-json\\/wp\\/v2\\/comments?post=1"}],"version-history":[{"href":"http:\\/\\/minilogbook.com\\/wp-json\\/wp\\/v2\\/posts\\/1\\/revisions"}],"wp:attachment":[{"href":"http:\\/\\/minilogbook.com\\/wp-json\\/wp\\/v2\\/media?parent=1"}],"wp:term":[{"taxonomy":"category","embeddable":true,"href":"http:\\/\\/minilogbook.com\\/wp-json\\/wp\\/v2\\/categories?post=1"},{"taxonomy":"post_tag","embeddable":true,"href":"http:\\/\\/minilogbook.com\\/wp-json\\/wp\\/v2\\/tags?post=1"}],"curies":[{"name":"wp","href":"https:\\/\\/api.w.org\\/{rel}","templated":true}]}}]'
```

**Comment by happyraul** [comment]
@minorsecond It seems your server may not be sending back a response containing a code and message. On mine I get something like this back for 404:

`{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}`

This results in an exception being raised like this:
`wordpress_json.WordpressError: 404 Not Found : [rest_no_route] No route was found matching the URL and request method`

**Comment by happyraul** [comment]
Version 0.2.3 has been released to fix this issue: https://pypi.python.org/pypi/wordpress_json/0.2.3

Thanks for reporting it and for the fix @droustchev
